# !!! THE PERMISSION FOR THE COMMANDS IS specu.moderate - YOU CANNOT CHANGE THAT

# Set the file with your own messages (e.g. custom, en_US, pl_PL)
messagesfile: en_US

# Set if you want the titles to be sent.
mutetitle: true
warntitle: true

# Set true/false if you want to turn on whitelist (or use /whitelist on/off)
whitelistenabled: false